# This is a basic workflow to help you get started with Actions

name: Docker Builds

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'dev'
      - 'v*.*.*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'
      - 'dev'
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-workspace:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: base-image/Dockerfile
            image: ghcr.io/shadowkrusha/base-workspace
    steps:
      # Get the repositery's code
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/build-image
        with:
          dockerfile: ${{ matrix.dockefile }}
          context: .
          image: ${{ matrix.image }}
